apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    token: abcdef.0123456789abcdef
    ttl: 24h0m0s
    usages:
      - signing
      - authentication
localAPIEndpoint:
  advertiseAddress: 192.168.1.12 #IP Узла
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: control-01.lan
  taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
clusterName: bnvkube.lan #Имя кластера
kubernetesVersion: 1.29.0 #Версия kubernetes
controlPlaneEndpoint: 192.168.1.12:7443 #IP на балансировщик (Обязательно если узлов Contr Plane больше 1)
certificatesDir: /etc/kubernetes/pki #Указывает, где хранить или искать все необходимые сертификаты.
imageRepository: registry.k8s.io
apiServer:
  timeoutForControlPlane: 4m0s
  extraArgs:
    bind-address: 0.0.0.0 #Для работы метрик
    service-cluster-ip-range: "10.10.0.0/16"
    service-node-port-range: 30000-32767
controllerManager:
  extraArgs:
    bind-address: 0.0.0.0 #Для работы метрик
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
    extraArgs:
      listen-metrics-urls: "http://0.0.0.0:2381" #Для работы метрик
networking: #Настройка внутренней сети кластера
  dnsDomain: cluster.local
  podSubnet: 10.20.0.0/16
  serviceSubnet: 10.10.0.0/16
scheduler:
  extraArgs:
    bind-address: 0.0.0.0 #Для работы метрик
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: 0.0.0.0
metricsBindAddress: 0.0.0.0:10249 #Для работы метрик
clusterCIDR: 10.20.0.0/16 #Диапазон CIDR модулей pod в кластере
mode: ipvs
ipvs:
  strictARP: True #Если вы используете kube-proxy в режиме IPVS, начиная с Kubernetes v1.14.2, вы должны включить строгий режим ARP.
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
clusterDNS:
  - 169.254.20.10 #IP DNS Сервера
clusterDomain: cluster.local
containerLogMaxSize: 50Mi # Default: "10Mi"
containerLogMaxFiles: 5 # Default: 5
systemReserved:
  memory: 512Mi
  cpu: 500m
  ephemeral-storage: 2Gi
